### ISSUE TITLE
review of ice flags

### ISSUE THREAD

**Issue by cnell-usgs** [USGS-VIZLAB/blitz-FY21Q3#4]
From the `.Rmd` , it's not clear that the target lists should be combined. I initially tried to run each chunk copy and pasted into `_targets.R` and it gave me an error: `Error: callr subprocess failed: object 'winter_data' not found`.  I think this was because it was disconnecting the target lists, here's my visnetwork output:
![image](https://user-images.githubusercontent.com/17803537/125133620-b4b9f200-e0cb-11eb-8d33-70c275f0a2c4.png)

When I combined in one list it worked. Here's my output for 3 states:
![gage_ice_popsicles](https://user-images.githubusercontent.com/17803537/125133774-f9458d80-e0cb-11eb-9378-4070fc645ae3.png)

Aside from that, looks good to me. Smart using the pipeline in the `.Rmd` like that

**Comment by lindsayplatt** [comment]
I think you should be able to just hit "knit" as you would normal Rmds and it will build the pipeline appropriately. There is a separate method for running them "interactively" (running each chunk) - I think you would change `tar_interactive` to TRUE here: https://github.com/USGS-VIZLAB/blitz-FY21Q3/blob/main/ice_flags/ice_pipeline.Rmd#L12. 

I realize my first sentence is misleading ... I was trying to compare it to a regular targets pipeline setup to help people understand but that probably isn't useful. I will update to reflect what I just said here.

**Comment by cnell-usgs** [comment]
I wasn't able to knit the `.Rmd` until after I created `_targets.R`. Otherwise I get this error: 
![image](https://user-images.githubusercontent.com/17803537/125311049-b9172280-e2f8-11eb-8c5e-cc4b902e2988.png)

**Comment by lindsayplatt** [comment]
Hmmm I don't get that error when I do it

**Comment by lindsayplatt** [comment]
OH what is your working directory?? I bet it is not `ice_flags/`. I think your working directory needs to match that of the `.Rmd`. Can you do `setwd("ice_flags")` and try again? Does that fix it?

**Comment by cnell-usgs** [comment]
No dice, `ice_flags` was my working directory.

**Comment by lindsayplatt** [comment]
Hmmm because it is autogenerating a `_targets.R` file for me and it looks like this:

```r
# Generated by targets: do not edit by hand
library(targets)
lapply(
  list.files(
    file.path("_targets_r", "globals"),
    pattern = "\\.R$",
    full.names = TRUE
  ),
  source
)
lapply(
  list.files(
    file.path("_targets_r", "targets"),
    pattern = "\\.R$",
    full.names = TRUE
  ),
  function(x) source(x)$value
)
```

**Comment by cnell-usgs** [comment]
:confused:

**Comment by cnell-usgs** [comment]
When I do `names(knitr::knit_engines$get())` targets is not listed for me. Based on this https://books.ropensci.org/targets/markdown.html I also would expect to have a target `.Rmd` template, but I do not. I'm up-to-date on version 0.4.2 of targets though.

Seems like I should be able to set the targets engine location like below, but I'm not sure where to find targets. Do you recall doing anything like this?
```
knitr::opts_chunk$set(engine.path = list(
  python = '~/anaconda/bin/python',
  ruby = '/usr/local/bin/ruby'
))

**Comment by lindsayplatt** [comment]
Woah nope. I barely had to do any setup. I just made the .Rmd. Ran things interactively as I developed and then once I was ready to run the whole thing I clicked knit. I wonder if there is some differences now that you are on Mac?

**Comment by cnell-usgs** [comment]
Tested on my PC and had the same issue

**Comment by lindsayplatt** [comment]
Boooo 😭 😭 I don't have too much time to troubleshoot right now but maybe further troubleshooting would be easier via screenshare and we can do that something in the next couple of days?

**Comment by lindsayplatt** [comment]
Figured it out! You need v0.5.0 or greater to use `targets` with Markdown. https://github.com/ropensci/targets/releases/tag/0.5.0
